#!/command/with-contenv bash
# shellcheck shell=bash
# =============================================================================
#  init-config  ·  s6-overlay oneshot
#  Validates environment variables and writes /etc/nextdns.conf
# =============================================================================

set -euo pipefail

log()  { printf '[tailwag] %s\n' "$*"; }
die()  { printf '[tailwag] FATAL: %s\n' "$*" >&2; exit 1; }

# --- Validate required variables ---------------------------------------------

if [[ -z "${NEXTDNS_PROFILE:-}" ]]; then
    die "NEXTDNS_PROFILE is required. Get yours at https://my.nextdns.io → Setup → Endpoints"
fi

if [[ ! "${NEXTDNS_PROFILE}" =~ ^[a-zA-Z0-9]{6,7}$ ]]; then
    die "Invalid NEXTDNS_PROFILE '${NEXTDNS_PROFILE}'. Expected 6-7 alphanumeric characters."
fi

if [[ -z "${TS_AUTHKEY:-}" ]]; then
    # Check if we have existing state (re-auth not needed)
    if [[ ! -d "${TS_STATE_DIR}" ]] || [[ -z "$(ls -A "${TS_STATE_DIR}" 2>/dev/null)" ]]; then
        die "TS_AUTHKEY is required for first-time setup. Use an auth key or OAuth client secret."
    fi
    log "No TS_AUTHKEY set, but existing state found in ${TS_STATE_DIR}. Re-using."
fi

# --- Write NextDNS configuration ---------------------------------------------

LISTEN="${NEXTDNS_LISTEN:-:53}"
CACHE="${NEXTDNS_CACHE_SIZE:-10MB}"
MAX_TTL="${NEXTDNS_MAX_TTL:-5s}"

log "Writing /etc/nextdns.conf (profile=${NEXTDNS_PROFILE}, cache=${CACHE}, ttl=${MAX_TTL})"

cat > /etc/nextdns.conf <<EOF
# Generated by Tailwag Docker init-config
profile ${NEXTDNS_PROFILE}
listen ${LISTEN}
cache-size ${CACHE}
max-ttl ${MAX_TTL}
report-client-info true
mdns disabled
auto-activate false
bogus-priv true
use-hosts true
discovery-dns 100.100.100.100
forwarder ts.net=100.100.100.100
EOF

# Append any extra nextdns args as config lines
if [[ -n "${NEXTDNS_EXTRA_ARGS:-}" ]]; then
    log "Appending NEXTDNS_EXTRA_ARGS to config"
    echo "${NEXTDNS_EXTRA_ARGS}" >> /etc/nextdns.conf
fi

# --- Ensure state directory exists -------------------------------------------

mkdir -p "${TS_STATE_DIR}" /var/run/tailscale
chmod 700 "${TS_STATE_DIR}"

log "Configuration ready."
