name: ShellCheck

on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: koalaman/shellcheck-action@v3
        with:
          files: >
            tailwag.sh
            docker/run
            docker/init-config.sh
            docker/tailscale-up.sh
            docker/rootfs/etc/s6-overlay/s6-rc.d/svc-nextdns/run
